### ISSUE TITLE
Bix Dev PedcbioPortal Support: add cancer type detailed to GMKF NBL samples

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#242]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

This info is missing and as a result, NBL samples don't get plotted
![image](https://user-images.githubusercontent.com/207034/139090587-9a9d7e26-71d6-4117-a6ba-3b2b585d396f.jpeg)

### Ticket will be considered resolved either by a successful PR with updated release if applicable, or a simple denial of the request backed by a good reason

**Comment by runjin326** [comment]
@jharenza, I looked into the `data_clinical_sample.txt` downloaded from the s3 bucket listed above but it seemed like the file already has cancer type information:
```
> check %>% filter(COHORT == "GMKF") %>% select(CANCER_TYPE, HISTOLOGY) %>% table()
                  HISTOLOGY
CANCER_TYPE        Neuroblastoma
  Embryonal tumors           344
> check %>% filter(COHORT == "GMKF") %>% filter(is.na(CANCER_TYPE)) %>% nrow()
[1] 0
```
Am I missing something?

**Comment by runjin326** [comment]
@jharenza, just to confirm, I am seeing that for other cancer types, they are using harmonized/integrated diagnosis as `CANCER_TYPE_DETAILED` and since NBL does not have that field, we should just use `HISTOLOGY`? 
Also, just want to confirm, we are using `harmonized_diagnosis` not `integrated_diagnosis` for `CANCER_TYPE_DETAILED` correct? Harmonized diagnosis field has entries that are NA in integrated - so just want to check.

**Comment by jharenza** [comment]
Oh yes, cancer type detailed - for TARGET samples, can we simply copy path dx to the harmonized diagnosis (can make a ticket please) in our histology file and then use that here? The harm dx should be absent of NAs (for PBTA, if subtyped, it was the integrated dx and if not, it was the pathology dx). That way, the harm dx will be complete.

**Comment by runjin326** [comment]
@jharenza, sure I will open ticket to use path dx as harmonized dx for TARGET samples and in the meantime, use path dx to populate `CANCER_TYPE_DETAILED` for now and update the file to S3 bucket once done.

**Comment by runjin326** [comment]
@jharenza, I have now generated the file with the [code in here](https://github.com/runjin326/CHOP_miscellaneous/blob/main/data_clinical_sample_fix.R). I have not uploaded the file yet since there are a couple things I want to confirm:
1) Not only GMKF NBL, TARGET AML and NBL also does not have `CANCER_TYPE_DETAILED` so I go ahead and added those back as well (344 NBL GMKF, 238 TARGET AML and 775 TARGET NBL)
2) I used `pathology_diagnosis` from the OT histologies file as `CANCER_TYPE_DETAILED` when available and when `pathology_diagnosis` is either `NA` or `Unknown`, I used `HISTOLOGY` column in `data_clinical_sample.txt`
3) There are 6 participants have multiple samples that are associated with different path dx - attached here.
[two_path_dx.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7462737/two_path_dx.txt)
     - 5 of them have both `Ganglioneuroblastoma, nodular` and `Neuroblastoma` and I picked `Ganglioneuroblastoma, nodular`
     - 1 of them have `Neuroblastoma` and `Unknown` and I picked `Neuroblastoma`
         - If we want to keep both entries, I can modify the code to keep both.
4) Additionally, one sample with BS ID `BS_0TCRV9AC` in PBTA cohort is a normal sample (when checked in OT histology) and hence no cancer related information in `data_clinical_sample.txt`. I kept it as is for now but I think we should probably remove it? 

Please let me know whether the above procedures make sense and I can make changes according to your feedback and upload the file when completed.

**Comment by migbro** [comment]
Along with the fix regarding #247 , @runjin326 has also addressed this: https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021

When v10 rolls along, it is preferred that the dx issue be resolved in the histologies file, unless it is anticipated that this will happen on occasion. In that case, the code can be updated to look for a "backup" field.

**Comment by migbro** [comment]
This has been pushed to prod after review from @runjin326 , I will consider this closed.

**Comment by jharenza** [comment]
This is still an issue in the histologies file. For cancers with no subtyping, we will need to add info to the harmonized diagnosis field. This is performed in molecular subtype integrate but hasn't been used on non-PBTA samples yet because they do not undergo subtyping. @ewafula and @runjin326 let's regroup on this.

**Comment by jharenza** [comment]
I updated this in #170
